ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS cargo TEXT NOT NULL DEFAULT '';
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS superior_id UUID REFERENCES usuarios(id) ON DELETE SET NULL;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS fecha_baja TIMESTAMPTZ;
CREATE TABLE IF NOT EXISTS impar_clientes_fuente (
  empresa_id UUID NOT NULL REFERENCES empresas(id) ON DELETE CASCADE,
  clave TEXT NOT NULL,
  contacto_id UUID NOT NULL REFERENCES contactos(id) ON DELETE CASCADE,
  datos JSONB NOT NULL,
  actualizado TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY(empresa_id,clave)
);
